# Generated by Selenium IDE
from selenium import webdriver
from selenium.webdriver.common.by import By


class TestESSAI():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_eSSAI(self):
    self.driver.get("https://tf.f80.fr/nfts-perso")
    self.driver.set_window_size(652, 737)
    self.driver.find_element(By.ID, "cmdMenu").click()
    self.driver.find_element(By.ID, "cmdMenu").click()
    self.driver.find_element(By.CSS_SELECTOR, "#cmdTokenizer > .mat-list-item-content").click()
    self.driver.find_element(By.CSS_SELECTOR, "#mat-tab-label-1-1 > .mat-tab-label-content").click()
    self.driver.find_element(By.CSS_SELECTOR, "#cdk-step-label-0-1 .mat-step-text-label").click()
    self.driver.find_element(By.CSS_SELECTOR, ".ng-tns-c193-15 > .ng-star-inserted:nth-child(4)").click()
    self.driver.find_element(By.ID, "txtTitle").send_keys("TOK A11top2")
    self.driver.find_element(By.ID, "txtPrice").send_keys("2")
    self.driver.find_element(By.CSS_SELECTOR, "#cdk-step-label-0-3 .mat-step-text-label").click()
    self.driver.find_element(By.CSS_SELECTOR, "#cdk-step-content-0-3 > .mat-vertical-content").click()
    self.driver.find_element(By.ID, "mat-input-4").send_keys("2")
    self.driver.find_element(By.CSS_SELECTOR, ".large-button > .mat-button-wrapper").click()
  
