appname: "CoinMaKer"
description: "Simple and free coin-maker and wallet for everyone"
logo: "./assets/coin.png"

min_gas_to_transfer: 50000000000000000
min_gas_to_create: 100000000000000000


labels:
  solde: "Votre solde"

messages:
  nomoney: "Aucune monnaie sélectionnée"

editor:
  author: "Herve Hoareau"
  name: "F80"
  link_author: "https://www.linkedin.com/in/hhoareau/"
  website: "https://f80.fr"


support:
  email: ""
  forum: "https://t.me/coinmaker_forum"
  faq: "https://elmoney.f80.fr/faqs"
  facebook: "https://facebook.com/page/coinmaker"
  website: ""
