appname: "TokenForge"
description: "Simple and free coin-maker and wallet for everyone"
logo: "./assets/coin.png"

min_gas_to_transfer: 50000000000000000
min_gas_to_create: 100000000000000000

#Taille maximum des fichiers utilisable avec les token
max_file_size: 1000000

labels:
  solde: "Votre solde"

messages:
  nomoney: "Aucune monnaie sélectionnée"

editor:
  author: "Herve Hoareau"
  name: "F80"
  link_author: "https://www.linkedin.com/in/hhoareau/"
  website: "https://f80.fr"


support:
  email: ""
  forum: "https://t.me/joinchat/Tuc8TPeJ_uw4N2U0"
  faq: "https://tf.f80.fr/faqs"
  facebook: "https://facebook.com/page/coinmaker"
  website: ""
