appname: "TokenForge"
description: "Simple and free coin-maker and wallet for everyone"
logo: "./assets/coin.png"

min_gas_to_transfer: 50000000000000000
min_gas_to_create: 100000000000000000

#Taille maximum des fichiers utilisable avec les token
max_file_size: 100000000000

labels:
  solde: "Votre solde"

messages:
  nomoney: "Aucune monnaie sélectionnée"

editor:
  author: "Herve Hoareau"
  name: "F80"
  link_author: "https://www.linkedin.com/in/hhoareau/"
  website: "https://f80.fr"

tags:
  default: "https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/120/apple/285/wrapped-gift_1f381.png"
  photo: "https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/120/apple/285/camera_1f4f7.png"
  souvenir: "https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/120/google/298/birthday-cake_1f382.png"
  jeu: "https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/120/apple/285/game-die_1f3b2.png"
  contrat: "https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/120/apple/285/scroll_1f4dc.png"
  secret: "https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/120/apple/285/old-key_1f5dd-fe0f.png"
  fichier: "https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/120/apple/285/file-folder_1f4c1.png"

tips:
  - A tout moment vous pouvez fabriquer une nouvelle monnaie et en envoyer à vos amis
  - A tout moment vous pouvez fabriquer de nouveaux NFT et les donner ou les vendres via la place de marché
  - N'hésitez pas à personnaliser votre compte depuis le menu "Mes préférences"
  - Si vous avez une question, consultez les FAQs. Si vous n'avez pas votre réponse, utiliser le Telegram de la communauté
  - Retrouvez tous vos NFTs (ceux que vous avez fabriqué mais également ceux que vous avez achetez) dans la rubrique Mes NFT
  - Dans TokenForge, tout le monde peut être créateur de NFT ou vendeur des NFTs des autres

support:
  email: ""
  forum: "https://t.me/joinchat/Tuc8TPeJ_uw4N2U0"
  faq: "https://tf.f80.fr/faqs"
  facebook: "https://facebook.com/page/coinmaker"
  website: ""
